module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'build',
        'ci',
        'chore',
        'revert',
        'security',
      ],
    ],
    'subject-case': [0],
    'header-max-length': [2, 'always', 100],
    'scope-case': [2, 'always', 'kebab-case'],
    'scope-empty': [2, 'never'],
    'scope-enum': [
      2,
      'always',
      [
        'auth',
        'rbac',
        'users',
        'workspaces',
        'projects',
        'api',
        'web',
        'db',
        'security',
        'ci',
        'infra',
        'docs',
        'design-ui',
        'design-tokens',
        'design-themes',
        'design-icons',
      ],
    ],
  },
};
