import pino from 'pino';

export const loggerRedactPaths = [
  'authorization',
  'headers.authorization',
  'headers.x-api-key',
  'headers.x-workspace-platform-key',
  'headers.cookie',
  'headers["x-api-key"]',
  'headers["X-Api-Key"]',
  'headers["x-workspace-platform-key"]',
  'headers["X-Workspace-Platform-Key"]',
  'req.headers.authorization',
  'req.headers.x-api-key',
  'req.headers.x-workspace-platform-key',
  'req.headers.cookie',
  'req.headers["x-api-key"]',
  'req.headers["X-Api-Key"]',
  'req.headers["x-workspace-platform-key"]',
  'req.headers["X-Workspace-Platform-Key"]',
  'cookie',
  'password',
  'passwordHash',
  'refreshToken',
  'refreshTokenHash',
  'accessToken',
  'token',
  'tokenHash',
  'apiKey',
  'api_key',
  'x-api-key',
  'xApiKey',
  'x-workspace-platform-key',
  'email',
  'contactEmail',
  'contactPhone',
  'permissionsOverride',
  '*.password',
  '*.passwordHash',
  '*.refreshToken',
  '*.refreshTokenHash',
  '*.accessToken',
  '*.token',
  '*.tokenHash',
  '*.authorization',
  '*.x-api-key',
  '*.x-workspace-platform-key',
  '*.secret',
  '*.apiKey',
  '*.api_key',
  '*.internalApiKey',
  '*.email',
  '*.contactEmail',
  '*.contactPhone',
  '*.permissionsOverride',
] as const;

export const appLogger = pino({
  level: process.env.LOG_LEVEL ?? 'info',
  redact: {
    paths: [...loggerRedactPaths],
    remove: true,
  },
  timestamp: pino.stdTimeFunctions.isoTime,
});

export const withBindings = (bindings: Record<string, unknown>) => appLogger.child(bindings);
