apiVersion: apps/v1
kind: Deployment
metadata:
  name: followup-api
  labels:
    app: followup-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: followup-api
  template:
    metadata:
      labels:
        app: followup-api
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: APP_ENV
              value: {{ .Values.env.APP_ENV | quote }}
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: followup-api-secrets
                  key: MONGO_URI
            - name: MONGO_DB_NAME
              value: test-zanetti
            - name: AUTH_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: followup-api-secrets
                  key: AUTH_JWT_SECRET
            - name: INTERNAL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: followup-api-secrets
                  key: INTERNAL_API_KEY
          readinessProbe:
            httpGet:
              path: /v1/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /v1/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
{{ toYaml .Values.resources | indent 12 }}
