apiVersion: v1
kind: Service
metadata:
  name: followup-api
spec:
  selector:
    app: followup-api
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  type: {{ .Values.service.type }}
