export const colors = {
  accent: {
    $accent: '#6266ef',
    '$on-accent': '#ffffff',
    '$on-accent-sub': '#e0e0e0',
    '$on-accent-disabled': '#b9b9b9',
    '$on-accent-light': '#474747',
    '$accent-hover': '#4e51c0',
    '$accent-active': '#3a3c92',
    '$accent-light': '#f6f8ff',
    '$accent-border': '#6266ef',
  },
  primary: {
    $primary: '#b1b9cd',
    '$on-primary': '#000000',
    '$on-primary-sub': '#474747',
    '$on-primary-sub-sidebar': '#585E70',
    '$on-primary-disabled': '#9e9e9e',
    '$on-primary-light': '#474747',
    '$primary-hover': '#969db3',
    '$primary-active': '#8991a6',
    '$primary-light': '#ebedf8',
    '$primary-border': '#ced4e6',
  },
  secondary: {
    $secondary: '#8a96f8',
    '$on-secondary': '#ffffff',
    '$on-secondary-sub': '#e0e0e0',
    '$on-secondary-disabled': '#b9b9b9',
    '$on-secondary-light': '#474747',
    '$secondary-hover': '#7d87f5',
    '$secondary-active': '#6266ef',
    '$secondary-light': '#f6f8ff',
    '$secondary-border': '#7d87f5',
  },
  tertiary: {
    $tertiary: '#6266ef',
    '$on-tertiary': '#ffffff',
    '$on-tertiary-sub': '#e0e0e0',
    '$on-tertiary-disabled': '#b9b9b9',
    '$on-tertiary-light': '#474747',
    '$tertiary-hover': '#4e51c0',
    '$tertiary-active': '#3a3c92',
    '$tertiary-light': '#f6f8ff',
    '$tertiary-border': '#4e51c0',
  },
  inverse: {
    $inverse: '#ffffff',
    '$on-inverse': '#3b3b3b',
    '$on-inverse-sub': '#5e5e5e',
    '$on-inverse-disabled': '#767676',
    '$inverse-hover': '#f1f1f1',
    '$inverse-active': '#e0e0e0',
    '$inverse-border': '#f1f1f1',
  },
  general: {
    $general: '#ffffff',
    '$on-general': '#3b3b3b',
    '$on-general-sub': '#767676',
    '$on-general-disabled': '#9e9e9e',
    '$general-hover': '#f8f8f8',
    '$general-active': '#f1f1f1',
    '$general-border': '#e0e0e0',
  },
  disabled: {
    $disabled: '#f1f1f1',
    '$on-disabled': '#b9b9b9',
  },
  negative: {
    $negative: '#767676',
    '$on-negative': '#ffffff',
    '$negative-hover': '#909090',
    '$on-negative-disabled': '#9e9e9e',
    '$on-negative-sub': '#e0e0e0',
    '$negative-border': '#3b3b3b',
  },
  canvas: {
    $canvas: '#f8f8f8',
  },
  danger: {
    $danger: '#ca4a46',
    '$danger-border': '#ca4a46',
    '$on-danger': '#ffffff',
    '$danger-hover': '#a33b38',
    '$danger-active': '#7e2a28',
    '$danger-light': '#feedeb',
  },
  info: {
    $info: '#4073d5',
    '$info-border': '#4073d5',
    '$on-info': '#ffffff',
    '$info-hover': '#2b64d1',
    '$info-active': '#1a4390',
    '$info-light': '#eaf1fe',
  },
  success: {
    $success: '#2e872b',
    '$success-border': '#2e872b',
    '$on-success': '#ffffff',
    '$success-hover': '#007c00',
    '$success-active': '#015300',
    '$success-light': '#ebf3ea',
  },
  warning: {
    $warning: '#a46a1d',
    '$warning-border': '#a46a1d',
    '$on-warning': '#ffffff',
    '$warning-hover': '#875200',
    '$warning-active': '#663d00',
    '$warning-light': '#f7f0e9',
  },
};
