import type { ConnectorCatalogItem } from "./types";

export const coreConnectors: ConnectorCatalogItem[] = [
  {
    id: "connector_gmail",
    name: "Gmail",
    group: "Communication",
    status: "coming_soon",
    brandId: "gmail",
    description: "Ingestion email bidirezionale con timeline cliente e contatori mail ricevute.",
    capabilities: ["Mail ingestion", "Thread matching", "Timeline events"],
    prerequisites: ["Google OAuth app"],
  },
  {
    id: "connector_outlook",
    name: "Outlook",
    group: "Communication",
    status: "beta",
    brandId: "outlook",
    description: "Sincronizzazione casella Outlook e automazioni follow-up su activity.",
    capabilities: ["Mail sync", "Calendar sync hooks", "Timeline events"],
    prerequisites: ["Azure app registration"],
    setupSummary: "Integrazione OAuth Outlook in arrivo. Per ricevere notifiche su eventi CRM (nuova trattativa, cambio stato) usa intanto i Webhook (tab Webhook) verso un workflow che invia email o crea attività Outlook.",
    relatedTab: "webhook",
  },
  {
    id: "connector_twilio",
    name: "WhatsApp (Twilio)",
    group: "Communication",
    status: "available",
    brandId: "twilio",
    description:
      "Collegamento una tantum: con Twilio attivo, messaggi e regole del tab Comunicazioni possono essere recapitati su WhatsApp (per workspace).",
    capabilities: ["Invio WhatsApp", "SMS (policy Twilio)", "Messaggio di prova (admin)"],
    prerequisites: ["Account Twilio", "Numero WhatsApp approvato o sandbox"],
    setupSummary:
      "Apri Configura e inserisci Account SID, Auth Token e numero mittente WhatsApp. Poi definisci messaggi e regole nel tab Comunicazioni.",
    relatedTab: "comunicazioni",
  },
  {
    id: "connector_meta_whatsapp",
    name: "WhatsApp (Meta Cloud API)",
    group: "Communication",
    status: "available",
    brandId: "meta",
    description:
      "Invio WhatsApp tramite template approvati su Meta (WhatsApp Cloud API). Se configurato, ha priorità su Twilio per il medesimo workspace.",
    capabilities: ["Invio solo template approvati", "Parametri da variabili CRM", "Prova invio (admin)"],
    prerequisites: ["App Meta", "Phone Number ID", "Token di accesso", "Template approvati in Meta"],
    setupSummary:
      "Inserisci Phone Number ID e access token (Graph API). Nei messaggi WhatsApp del tab Comunicazioni indica nome template Meta, lingua e variabili nello stesso ordine dei placeholder {{1}}, {{2}}, …",
    relatedTab: "comunicazioni",
  },
  {
    id: "connector_mailchimp",
    name: "Mailchimp",
    group: "Marketing",
    status: "beta",
    brandId: "mailchimp",
    description:
      "Segmenti marketing da profili CRM e trigger campagne da eventi trattativa. L’attivazione è commerciale: nessuna auto-provisioning dal portale.",
    capabilities: ["Segment sync", "Campaign trigger", "Bounce feedback"],
    prerequisites: ["Mailchimp API key", "Modulo abilitato da Tecma"],
  },
  {
    id: "connector_activecampaign",
    name: "ActiveCampaign",
    group: "Marketing",
    status: "beta",
    description:
      "Automazioni e liste collegate al CRM. Stesso modello di Mailchimp: attivazione solo dopo accordo commerciale con Tecma.",
    capabilities: ["List sync", "Automation hooks", "Event triggers"],
    prerequisites: ["Account ActiveCampaign", "Modulo abilitato da Tecma"],
  },
  {
    id: "connector_n8n",
    name: "n8n",
    group: "Workflow Automation",
    status: "available",
    brandId: "n8n",
    description: "Event bus out/in per orchestrare workflow custom senza sviluppo backend dedicato.",
    capabilities: ["Webhook out", "Webhook in", "Retry hooks"],
    prerequisites: ["n8n endpoint", "Signing secret"],
    setupSummary: "Nel tab Webhook aggiungi un webhook con URL = URL del nodo Webhook del workflow n8n. Eventi disponibili: request.created, request.status_changed, client.created, calendar.event.created. Il payload viene inviato in POST con header X-Webhook-Signature (HMAC) se imposti un secret.",
    relatedTab: "webhook",
  },
  {
    id: "connector_salesforce",
    name: "Salesforce",
    group: "CRM/Lead Sources",
    status: "coming_soon",
    brandId: "salesforce",
    description: "Sincronizzazione lead/deal multi-tenant con mapping campo configurabile.",
    capabilities: ["Lead sync", "Deal sync", "Custom field mapping"],
    prerequisites: ["Salesforce connected app"],
  },
  {
    id: "connector_webflow",
    name: "Webflow",
    group: "Website/CMS",
    status: "coming_soon",
    brandId: "webflow",
    description: "Pubblicazione listing apartment-first su siti Webflow con sync near real-time.",
    capabilities: ["Listing publish", "Media sync", "Status update"],
    prerequisites: ["Webflow API token", "Collection mapping"],
  },
  {
    id: "connector_looker",
    name: "Looker Studio",
    group: "Data/BI",
    status: "available",
    brandId: "looker_studio",
    description:
      "Ponte verso reportistica Google: dataset da listati pubblici, metriche pipeline e KPI commerciali in dashboard condivise, con possibilità di refresh schedulato e tracciamento per audit interno. Si integra con l’API pubblica listings e con catene n8n / Sheet per data mart leggeri.",
    capabilities: [
      "Dataset & connector Looker",
      "Scheduled refresh",
      "Schema e metriche custom",
      "API listings → blend",
      "Dashboard condivise",
      "Governance visibilità",
    ],
    prerequisites: ["Destination connector o Custom API", "Progetti/workspace selezionati"],
    setupSummary:
      "Endpoint GET e POST /v1/public/listings (nessuna auth, 60 req/min). Per Looker Studio: connettore Community nel repo (connectors/looker-studio) con README per deploy; oppure Custom API / Google Sheet / n8n che chiamano l'API.",
    relatedTab: "api",
  },
  {
    id: "connector_power_bi",
    name: "Microsoft Power BI",
    group: "Data/BI",
    status: "coming_soon",
    brandId: "power_bi",
    description:
      "Pubblicazione di dataset e report aziendali su workspace Power BI: semantic model su trattative, immobili e forecast, con aggiornamento incrementale e distribuzione tramite app Tecma o embedding in portali interni.",
    capabilities: ["Dataset gateway", "DirectQuery / import", "RLS per ruolo", "Refresh pianificato", "Alert metriche"],
    prerequisites: ["Azure AD / Power BI Pro o Premium", "Permessi dataset"],
  },
  {
    id: "connector_tableau",
    name: "Tableau",
    group: "Data/BI",
    status: "coming_soon",
    brandId: "tableau",
    description:
      "Flusso dati verso Tableau Cloud o Server per analisi visuali avanzate, storyboard executive e pubblicazione su canali sicuri con filtri per progetto e brand.",
    capabilities: ["Hyper extract", "Live query", "Carte e dashboard", "Subscription report"],
    prerequisites: ["Tableau Cloud / Server", "Account connettore dati"],
  },
  {
    id: "connector_snowflake",
    name: "Snowflake",
    group: "Data/BI",
    status: "coming_soon",
    brandId: "snowflake",
    description:
      "Replica e modellazione dati CRM in un data warehouse cloud: staging eventi, snapshot trattative e tabelle curate per BI e data science, con separazione per tenant workspace.",
    capabilities: ["Landing zone", "CDC / merge", "Viste curate", "Time travel audit", "Share sicuro"],
    prerequisites: ["Account Snowflake", "Ruolo e warehouse dedicati"],
  },
  {
    id: "connector_bigquery",
    name: "Google BigQuery",
    group: "Data/BI",
    status: "coming_soon",
    brandId: "bigquery",
    description:
      "Caricamento near real-time in dataset GCP per analisi SQL, dashboard Looker Studio nativo e integrazione con Vertex / GA4 BigQuery export in un unico perimetro dati.",
    capabilities: ["Streaming insert", "Partizionamento", "Scheduled query", "IAM & row policy"],
    prerequisites: ["Progetto GCP", "Service account con scope BigQuery"],
  },
  {
    id: "connector_metabase",
    name: "Metabase",
    group: "Data/BI",
    status: "coming_soon",
    brandId: "metabase",
    description:
      "Self-service analytics open source: domande salvate, dashboard operative per vendor e pulse su soglie (lead, conversioni, SLA) senza dipendere da un team data dedicato.",
    capabilities: ["SQL / GUI query", "Dashboard & pulses", "Embedding", "Collection per team"],
    prerequisites: ["Istanza Metabase", "Database collegato o API bridge"],
  },
  {
    id: "connector_grafana",
    name: "Grafana",
    group: "Data/BI",
    status: "coming_soon",
    brandId: "grafana",
    description:
      "Osservabilità operativa su metriche CRM e integrazioni: salute webhook, code messaggi, errori API e SLO pipeline dati, affiancata a dashboard classiche di business.",
    capabilities: ["Datasource plugin", "Alerting", "Loki / Prometheus hook", "Panel condivisi"],
    prerequisites: ["Stack Grafana", "Endpoint metriche esposto"],
  },
  {
    id: "connector_databricks",
    name: "Databricks",
    group: "Data/BI",
    status: "coming_soon",
    brandId: "databricks",
    description:
      "Lakehouse per workload analytics e ML: feature store su clienti e immobili, training modelli scoring e batch scoring collegati agli eventi Tecma.",
    capabilities: ["Delta Lake", "Jobs schedulati", "Unity Catalog", "MLflow experiment"],
    prerequisites: ["Workspace Databricks", "Service principal"],
  },
  {
    id: "connector_google_analytics_4",
    name: "Google Analytics 4",
    group: "Data/BI",
    status: "coming_soon",
    brandId: "google_analytics",
    description:
      "Allineamento tra traffico siti/portali e funnel CRM: attribuzione campagne, eventi chiave e export BigQuery per unificare marketing intelligence con le trattative.",
    capabilities: ["Event stream", "Conversioni", "Link BigQuery", "Audience sync (roadmap)"],
    prerequisites: ["Property GA4", "Accesso API Data"],
  },
  {
    id: "connector_google_sheets_export",
    name: "Google Sheets",
    group: "Data/BI",
    status: "coming_soon",
    brandId: "google_sheets_export",
    description:
      "Export controllato verso fogli per ufficio commerciale e amministrazione: snapshot listati, pivot su lead e consegne periodiche senza esporre l’intero database.",
    capabilities: ["Range sync", "Append righe", "Trigger tempo", "Condivisione team"],
    prerequisites: ["OAuth Google Workspace", "ID foglio e tab"],
  },
  {
    id: "connector_airflow",
    name: "Apache Airflow",
    group: "Data/BI",
    status: "coming_soon",
    brandId: "airflow",
    description:
      "Orchestrazione ETL/ELT: DAG che orchestrano estrazione da Tecma, trasformazioni e caricamento verso warehouse o lake, con retry, SLA e notifiche su fallimenti.",
    capabilities: ["DAG scheduling", "Sensor & operator", "Backfill", "Lineage base"],
    prerequisites: ["Airflow 2.x", "Connessioni DB/API"],
  },
  {
    id: "connector_dbt",
    name: "dbt",
    group: "Data/BI",
    status: "coming_soon",
    brandId: "dbt",
    description:
      "Trasformazioni SQL versionate sui dati replicati: modelli staging → mart per KPI immobiliari e vendita, test di qualità e documentazione auto-generata.",
    capabilities: ["Modelli & test", "Docs site", "CI su warehouse", "Snapshot slowly changing"],
    prerequisites: ["dbt Core o Cloud", "Target warehouse (es. BigQuery, Snowflake)"],
  },
  {
    id: "connector_docusign",
    name: "DocuSign",
    group: "Docs/Signature",
    status: "coming_soon",
    brandId: "docusign",
    description:
      "Standard de facto per firma elettronica avanzata: generazione buste da template, flussi multi-firmatario, prove di consegna e integrazione con stati trattativa e conservazione documentale.",
    capabilities: [
      "Envelope & template dinamici",
      "Firma remota qualificata (perimetro legale)",
      "Webhook stato firma",
      "Audit trail completo",
      "Allegati e tabella campi",
      "Ruoli e ordine firma",
    ],
    prerequisites: ["Account DocuSign", "App integrata OAuth", "Template legali approvati"],
  },
  {
    id: "connector_teamsystem",
    name: "TeamSystem",
    group: "Docs/Signature",
    status: "coming_soon",
    brandId: "teamsystem",
    description:
      "Ponte con l’ecosistema gestionale italiano (documenti, contabilità, fatturazione elettronica): riferimenti documento, protocolli e stati contabili allineati a cliente e trattativa, per chi opera con TS CROSS, TS Digital o moduli verticali compatibili.",
    capabilities: [
      "Riferimenti documento / protocollo",
      "Sync anagrafiche e partite",
      "Stati fattura e incasso",
      "Codici contabili e centri di costo",
      "Collegamento mandati / incarichi",
    ],
    prerequisites: ["Licenza e API TeamSystem abilitate", "Mapping società / CIG / regole IVA", "Accordo progetto con Tecma"],
  },
  {
    id: "connector_adobe_sign",
    name: "Adobe Acrobat Sign",
    group: "Docs/Signature",
    status: "coming_soon",
    brandId: "adobe_sign",
    description:
      "Workflow di firma nel perimetro Adobe Document Cloud, ideale per organizzazioni già su Creative/Document Cloud: accordi multi-step, brand kit e conformità con archivi aziendali.",
    capabilities: ["Agreement API", "Mega sign", "Autenticazione forte", "Archiviazione Adobe"],
    prerequisites: ["Adobe Sign Enterprise", "Technical account"],
  },
  {
    id: "connector_dropbox_sign",
    name: "Dropbox Sign",
    group: "Docs/Signature",
    status: "coming_soon",
    brandId: "dropbox_sign",
    description:
      "Firma semplice e API-first (ex HelloSign): embed in portali cliente, template ripetibili e tracking stato per contratti standard immobiliari.",
    capabilities: ["Template API", "Embedded signing", "Campi obbligatori", "Reminder automatici"],
    prerequisites: ["Account Dropbox Sign", "API key applicazione"],
  },
  {
    id: "connector_pandadoc",
    name: "PandaDoc",
    group: "Docs/Signature",
    status: "coming_soon",
    brandId: "pandadoc",
    description:
      "Documenti commerciali con CPQ leggero: proposte con listino, approvazioni interne e firma in un’unica esperienza collegata al CRM.",
    capabilities: ["Editor documenti", "Approvazioni", "Pagamenti (Stripe)", "CRM sync"],
    prerequisites: ["Workspace PandaDoc", "Token API"],
  },
  {
    id: "connector_yousign",
    name: "Yousign",
    group: "Docs/Signature",
    status: "coming_soon",
    brandId: "yousign",
    description:
      "Firma elettronica qualificata con focus UE e ID wallet: adatta a conformità eIDAS e flussi immobiliari con identificazione rafforzata.",
    capabilities: ["Procedure qualificate", "OTP / video ID", "Conservazione probatoria", "API v3"],
    prerequisites: ["Account Yousign", "Ambiente sandbox / produzione"],
  },
  {
    id: "connector_slack",
    name: "Slack",
    group: "Productivity/Collab",
    status: "coming_soon",
    brandId: "slack",
    description: "Notifiche operative vendor_manager/admin su eventi critici.",
    capabilities: ["Channel alerts", "Action digests", "Mention policies"],
    prerequisites: ["Slack app token"],
  },
  {
    id: "connector_meta_lead_ads",
    name: "Meta Lead Ads",
    group: "CRM/Lead Sources",
    status: "coming_soon",
    brandId: "meta",
    description: "Ricezione automatica lead da campagne Facebook/Instagram Lead Ads nel CRM.",
    capabilities: ["Lead ingestion", "Mapping campi", "Sync near-real-time"],
    prerequisites: ["App Meta Business", "Pagina Facebook collegata"],
  },
  {
    id: "connector_google_ads",
    name: "Google Ads / LSA",
    group: "CRM/Lead Sources",
    status: "coming_soon",
    brandId: "google_ads",
    description: "Importazione lead da Google Ads (form extension) e Local Services Ads nel CRM.",
    capabilities: ["Lead import", "Conversion tracking", "LSA sync"],
    prerequisites: ["Account Google Ads", "OAuth Google"],
  },
  {
    id: "connector_portali_immobiliari",
    name: "Portali Immobiliari",
    group: "CRM/Lead Sources",
    status: "coming_soon",
    brandId: "portali_immobiliari",
    description: "Ricezione lead da portali immobiliari (Immobiliare.it, Idealista, Casa.it e altri) tramite parsing email o API dedicata.",
    capabilities: ["Lead ingestion", "Dedup automatico", "Multi-portale"],
    prerequisites: ["Account portale attivo", "Configurazione email o API"],
  },
  {
    id: "connector_zapier",
    name: "Zapier / Make",
    group: "Workflow Automation",
    status: "coming_soon",
    brandId: "zapier",
    description: "Collegamento a migliaia di app tramite Zapier o Make (Integromat). Trigger e azioni CRM senza codice.",
    capabilities: ["Trigger eventi CRM", "Azioni bidirezionali", "No-code workflows"],
    prerequisites: ["Account Zapier o Make"],
  },
  {
    id: "connector_hubspot",
    name: "HubSpot",
    group: "CRM/Lead Sources",
    status: "coming_soon",
    brandId: "hubspot",
    description: "Sincronizzazione contatti e deal con HubSpot CRM per pipeline marketing e vendite unificate.",
    capabilities: ["Contact sync", "Deal sync", "Custom properties"],
    prerequisites: ["Account HubSpot", "App privata o OAuth"],
  },
  {
    id: "connector_sumsub",
    name: "Sumsub",
    group: "Compliance",
    status: "available",
    description:
      "KYC e AML tramite Sumsub: verifica documento, screening e stati sul cliente. Richiede credenziali app e URL webhook verso questo backend.",
    capabilities: ["KYC", "AML screening", "SDK Web", "Webhook"],
    prerequisites: ["Account Sumsub", "Level name in dashboard", "Webhook secret"],
    setupSummary:
      "Inserisci App token, Secret key, Level name (come in Sumsub) e Webhook secret. In Sumsub imposta l’URL webhook: base API + /v1/webhooks/sumsub/{workspaceId}. Vedi docs/AML_COMPLIANCE.md sul server.",
  },
  {
    id: "connector_onfido",
    name: "Onfido",
    group: "Compliance",
    status: "coming_soon",
    description: "Verifica identità documentale e liveness. In roadmap come secondo connettore.",
    capabilities: ["Document check", "Liveness", "Watchlist"],
    prerequisites: ["Account Onfido"],
  },
  {
    id: "connector_complyadvantage",
    name: "ComplyAdvantage",
    group: "Compliance",
    status: "coming_soon",
    description: "Screening PEP e sanzioni. In roadmap.",
    capabilities: ["PEP", "Sanzioni", "Adverse media"],
    prerequisites: ["Account ComplyAdvantage"],
  },
  {
    id: "connector_trulioo",
    name: "Trulioo",
    group: "Compliance",
    status: "coming_soon",
    description: "Verifica identità globale. In roadmap.",
    capabilities: ["Identity network", "KYC"],
    prerequisites: ["Account Trulioo"],
  },
  {
    id: "connector_veriff",
    name: "Veriff",
    group: "Compliance",
    status: "coming_soon",
    description: "Video-identità e documenti. In roadmap.",
    capabilities: ["IDV", "AML"],
    prerequisites: ["Account Veriff"],
  },
  {
    id: "connector_microsoft_teams",
    name: "Microsoft Teams",
    group: "Productivity/Collab",
    status: "coming_soon",
    brandId: "teams",
    description: "Notifiche e card adattive su canali team per eventi CRM e digest operativi.",
    capabilities: ["Channel posts", "Adaptive cards", "Bot / webhook"],
    prerequisites: ["Azure AD app", "Teams admin consent"],
  },
  {
    id: "connector_zendesk",
    name: "Zendesk",
    group: "Communication",
    status: "coming_soon",
    brandId: "zendesk",
    description: "Allineamento ticket supporto con anagrafica cliente e trattative per SLA e handoff commerciale.",
    capabilities: ["Ticket sync", "Utente ↔ cliente", "Macro e trigger"],
    prerequisites: ["Account Zendesk", "API token"],
  },
  {
    id: "connector_sendgrid",
    name: "SendGrid",
    group: "Communication",
    status: "coming_soon",
    brandId: "sendgrid",
    description: "Email transazionali e di sistema con tracking aperture/clic e gestione bounce/complaint.",
    capabilities: ["Transactional API", "Templates", "Event webhook"],
    prerequisites: ["API key SendGrid", "Dominio autenticato (SPF/DKIM)"],
  },
  {
    id: "connector_calendly",
    name: "Calendly",
    group: "Communication",
    status: "coming_soon",
    brandId: "calendly",
    description: "Sincronizzazione appuntamenti prenotati con calendario e trattative (lead qualification).",
    capabilities: ["Booking webhook", "Invite sync", "CRM activity"],
    prerequisites: ["Calendly account", "Personal access token"],
  },
  {
    id: "connector_pipedrive",
    name: "Pipedrive",
    group: "CRM/Lead Sources",
    status: "coming_soon",
    brandId: "pipedrive",
    description: "Replica bidirezionale deal e organizzazioni per team che usano Pipedrive accanto al CRM Tecma.",
    capabilities: ["Deal sync", "Organization mapping", "Activity mirror"],
    prerequisites: ["API token Pipedrive", "Mapping pipeline"],
  },
  {
    id: "connector_typeform",
    name: "Typeform",
    group: "CRM/Lead Sources",
    status: "coming_soon",
    brandId: "typeform",
    description: "Creazione lead e aggiornamento profilo da risposte form (hidden fields, scoring).",
    capabilities: ["Webhook risposte", "Hidden CRM fields", "Dedup"],
    prerequisites: ["Typeform account", "Personal token"],
  },
  {
    id: "connector_linkedin_lead_gen",
    name: "LinkedIn Lead Gen",
    group: "CRM/Lead Sources",
    status: "coming_soon",
    brandId: "linkedin",
    description: "Import lead da moduli Sponsored Content e Lead Gen Forms nel funnel CRM.",
    capabilities: ["Lead sync", "Campo mapping", "Campagna ↔ sorgente"],
    prerequisites: ["LinkedIn Campaign Manager", "Lead Gen Forms"],
  },
  {
    id: "connector_stripe",
    name: "Stripe",
    group: "Payments & Billing",
    status: "coming_soon",
    brandId: "stripe",
    description: "Allineamento pagamenti, abbonamenti e ricevute con trattative e documentazione commerciale.",
    capabilities: ["Payment status", "Customer link", "Webhook eventi"],
    prerequisites: ["Account Stripe", "Webhook signing secret"],
  },
  {
    id: "connector_paypal",
    name: "PayPal",
    group: "Payments & Billing",
    status: "coming_soon",
    brandId: "paypal",
    description: "Notifiche IPN / webhooks per incassi e contestazioni collegati a ordini e clienti.",
    capabilities: ["Payment capture", "Refund events", "Dispute hooks"],
    prerequisites: ["Business PayPal", "Webhook / IPN endpoint"],
  },
];
