apiVersion: apps/v1
kind: Deployment
metadata:
  name: followup-web
  labels:
    app: followup-web
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: followup-web
  template:
    metadata:
      labels:
        app: followup-web
    spec:
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
