apiVersion: v1
kind: Service
metadata:
  name: followup-web
spec:
  selector:
    app: followup-web
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  type: {{ .Values.service.type }}
