sonar.sourceEncoding=UTF-8
sonar.projectKey=${env.CI_PROJECT_NAME}
# https://docs.sonarqube.org/latest/analysis/ci-integration-overview/
# Setting sonar.qualitygate.wait to true forces the analysis step to poll your SonarQube instance 
# until the Quality Gate status is available"
sonar.qualitygate.wait=true
# Coverage report
sonar.javascript.lcov.reportPaths=${env.CI_PROJECT_DIR}/coverage/lcov.info
## https://community.sonarsource.com/t/how-do-sonarcloud-properties-work-in-relation-to-each-other/33004
# Sources
sonar.sources=src
# Tests
sonar.tests=src/__tests__/*.spec.ts,s
# Inclusions
sonar.test.inclusions=src/**/*
# Duplication exclusions
sonar.exclusions=sonar-project.properties,coverage/**/*,build/**/*
